title: Ayaoba
email: essy@gmail.com
description: >- # this means to ignore newlines until "
  Tech Stories
# url: "https://patdryburgh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
twitter_username: patdryburgh
github_username:  patdryburgh

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
permalink: /:categories/:title/
collections:
  posts:
    output: true
    permalink: /blog/:title